In [ ]:
for condition:
    statement1
    statement2
statement3

In [2]:
list(range(0,6))

[0, 1, 2, 3, 4, 5]

In [3]:
range(0,7)

range(0, 7)

In [5]:
list(range(0,9,2))

[0, 2, 4, 6, 8]

In [6]:
for i in range(0,6):
    print(i)
print('Out of the loop')

0
1
2
3
4
5
Out of the loop


In [7]:
for i in [1,2,3,4]:
    print(i)

1
2
3
4


In [8]:
for i in [10,20,30]:
    print(i)

10
20
30


In [9]:
for i in range(0,6):
    print(i)
    print('Hi')

0
Hi
1
Hi
2
Hi
3
Hi
4
Hi
5
Hi


In [10]:
for i in range(0,6):
print(i)
    print('Hi')

IndentationError: expected an indented block (<ipython-input-10-4312512e0b53>, line 2)

In [19]:
names=['Aastha','Dim','Sheen','Shiv']
rollnum=[1,2,3,4]

In [17]:
for n in names:
    print(n)

Aastha
Dim
Sheen
Shiv


In [25]:
for (n,r) in zip(names,rollnum):
    print('Hello ',n,', your roll number is: ',r)

Hello  Aastha , your roll number is:  1
Hello  Dim , your roll number is:  2
Hello  Sheen , your roll number is:  3
Hello  Shiv , your roll number is:  4


In [26]:
section=['sales','marketing','finance','sales']

In [29]:
for (n,s) in zip(names,section):
    print(n,'is working as a',s,'intern.')

Aastha is working as a sales intern.
Dim is working as a marketing intern.
Sheen is working as a finance intern.
Shiv is working as a sales intern.


In [2]:
sales=[2343,5443,2334,4433]
profit=[435,334,234,333 ]


In [32]:
profitratio=[]
for i in range(0,len(sales)):
    profitratio.append(profit[i]/sales[i])
profitratio

[0.1856594110115237,
 0.06136321881315451,
 0.10025706940874037,
 0.07511842995713963]

In [1]:
import numpy as np

In [3]:
sales_array=np.array(sales)

In [4]:
profit_array=np.array(profit)

In [5]:
profit_array/sales_array

array([0.18565941, 0.06136322, 0.10025707, 0.07511843])

In [6]:
list1=[10,5.5,'R',True]

In [8]:
array1=np.array(list1)

In [9]:
array1

array(['10', '5.5', 'R', 'True'], dtype='<U32')

In [10]:
list2=[10,5.5,True]

In [11]:
array2=np.array(list2)

In [12]:
array2

array([10. ,  5.5,  1. ])

In [13]:
#list- takes the priority of the data type as it is
#array- takes the priority as string>float>integer>boolean

In [14]:
sales

[2343, 5443, 2334, 4433]

In [15]:
sales*2

[2343, 5443, 2334, 4433, 2343, 5443, 2334, 4433]

In [16]:
sales_array*2

array([ 4686, 10886,  4668,  8866])

In [17]:
#list-when you want to multiply a number with list it duplicates the value number of times it is multiplied
#array-performs actual multiplication with each value present in the array

In [20]:
 sales_array1=sales_array[1:3]  #values would be saved in same ram 
                                #any changes made in one array would be reflected on other arrray too

In [23]:
sales_array

array([2343, 2222, 2334, 4433])

In [19]:
sales_array1

array([5443, 2334])

In [22]:
sales_array1[0]=2222

In [24]:
sales_array1

array([2222, 2334])

In [25]:
sales_array2=sales_array1.copy() #to prevent changes use copy function

In [26]:
sales_array2

array([2222, 2334])

In [27]:
sales_array2[0]=1000

In [29]:
sales_array2

array([1000, 2334])

In [30]:
sales_array1

array([2222, 2334])

In [31]:
type(sales_array)

numpy.ndarray

In [33]:
sales_us=[2323,4334,3344,3233]
sales_eu=[5545,6667,4455,3444]
sales_jp=[5444,3443,4445,6555]

In [34]:
sales_matrix=np.array([sales_us,sales_eu,sales_jp])

In [35]:
sales_matrix

array([[2323, 4334, 3344, 3233],
       [5545, 6667, 4455, 3444],
       [5444, 3443, 4445, 6555]])

In [37]:
profit_matrix=np.array([[435,566,555,444],[676,434,565,333],[654,777,566,656]])

In [38]:
profit_matrix

array([[435, 566, 555, 444],
       [676, 434, 565, 333],
       [654, 777, 566, 656]])

In [39]:
profit_ratio=profit_matrix/sales_matrix

In [40]:
profit_ratio

array([[0.18725786, 0.13059529, 0.1659689 , 0.13733375],
       [0.12191163, 0.06509675, 0.12682379, 0.0966899 ],
       [0.12013226, 0.22567528, 0.12733408, 0.10007628]])

In [42]:
sales_matrix[1][2]

4455

In [43]:
rdict={'US':0,'EU':1,'JP':2}

In [44]:
qdict={'Q1':0,'Q2':1,'Q3':2,'Q4':3}

In [46]:
sales_matrix[rdict['EU']][qdict['Q3']]

4455

In [48]:
sales_array=np.array([2343,4434,333,4544,6676,8878,6676,9878,5678,7878,3454,8759])

In [49]:
sales_array

array([2343, 4434,  333, 4544, 6676, 8878, 6676, 9878, 5678, 7878, 3454,
       8759])

In [52]:
np.reshape(sales_array,(3,4),'C')

array([[2343, 4434,  333, 4544],
       [6676, 8878, 6676, 9878],
       [5678, 7878, 3454, 8759]])

In [51]:
np.reshape(sales_array,(3,4),'F')

array([[2343, 4544, 6676, 7878],
       [4434, 6676, 9878, 3454],
       [ 333, 8878, 5678, 8759]])